// File generated using battery::embed (https://github.com/batterycenter/embed)
// Embedded file: '${FILENAME}' as '${IDENTIFIER}'
// Filesize: ${FILESIZE} bytes
// DO NOT EDIT THIS FILE!!!

#include "battery/embed.hpp"

namespace b {

EmbedInternal::EmbeddedFile EmbedInternal::${IDENTIFIER} = {
  std::string_view(
      ${GENERATED_BYTE_ARRAY},
      ${FILESIZE}
  )
  , "${FILENAME}"
#ifndef B_PRODUCTION_MODE
  , "${FULL_PATH}"
#endif // !B_PRODUCTION_MODE
};

} // namespace b
